apiVersion: v2
name: ortelius-scec
description: Ortelius v11 Supply Chain Evidence Catalog
home: https://www.ortelius.io
icon: https://ortelius.github.io/ortelius-charts/logo.png
keywords:
  - Service Catalog
  - Microservices
  - SBOM
  - Supply Chain
  - Evidence Catalog
type: application
version: 11.0.0
appVersion: 11.0.0
